<?php

namespace Database\Seeders;

use App\Models\Participant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParticipantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $participants = [
            [
                'name' => 'AnnaGazanis',
                'is_new' => false,
                'twitch_username' => 'annagazanis',
                'youtube_url' => 'https://www.youtube.com/@AnnaGazanis',
                'twitch_url' => 'http://twitch.tv/annagazanis',
            ],
            [
                'name' => 'Arfore',
                'is_new' => false,
                'twitch_username' => 'Arfore',
                'youtube_url' => 'https://www.youtube.com/@Arfore',
                'twitch_url' => 'http://twitch.tv/Arfore',
            ],
            [
                'name' => 'AwesomeElina',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@Elinski',
                'twitch_url' => null,
            ],
            [
                'name' => 'baastiZockt',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/baastizockt',
                'twitch_url' => null,
            ],
            [
                'name' => 'BastiGHG',
                'is_new' => false,
                'twitch_username' => 'BastiGHG',
                'youtube_url' => 'https://www.youtube.com/@BastiGHG',
                'twitch_url' => 'http://twitch.tv/bastighg',
            ],
            [
                'name' => 'Benx',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@benx',
                'twitch_url' => null,
            ],
            [
                'name' => 'Blizzor',
                'is_new' => false,
                'twitch_username' => 'blizzor',
                'youtube_url' => 'https://www.youtube.com/c/Blizzor',
                'twitch_url' => 'https://www.twitch.tv/blizzor',
            ],
            [
                'name' => 'Caravas',
                'is_new' => false,
                'twitch_username' => 'caravasyt',
                'youtube_url' => 'https://www.youtube.com/c/Caravas',
                'twitch_url' => 'https://www.twitch.tv/caravasyt',
            ],
            [
                'name' => 'CastCrafter',
                'is_new' => false,
                'twitch_username' => 'CastCrafter',
                'youtube_url' => 'https://www.youtube.com/c/CastCrafter',
                'twitch_url' => 'http://twitch.tv/castcrafter',
            ],
            [
                'name' => 'ChaosFlo44',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@Chaosflo44',
                'twitch_url' => null,
            ],
            [
                'name' => 'Chefstrobel',
                'is_new' => false,
                'twitch_username' => 'chefstrobel',
                'youtube_url' => 'https://www.youtube.com/c/Chefstrobel',
                'twitch_url' => 'http://twitch.tv/chefstrobel',
            ],
            [
                'name' => 'Clym',
                'is_new' => false,
                'twitch_username' => 'clym',
                'youtube_url' => 'https://www.youtube.com/c/TheClym',
                'twitch_url' => 'https://www.twitch.tv/clym',
            ],
            [
                'name' => 'Crocodileandy',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/c/Crocodileandy',
                'twitch_url' => null,
            ],
            [
                'name' => 'Debitor',
                'is_new' => false,
                'twitch_username' => 'debitorlp',
                'youtube_url' => 'https://www.youtube.com/c/Debitor',
                'twitch_url' => 'http://twitch.tv/debitorlp',
            ],
            [
                'name' => 'earliboy',
                'is_new' => false,
                'twitch_username' => 'earliboy',
                'youtube_url' => 'https://www.youtube.com/c/earliboy',
                'twitch_url' => 'https://www.twitch.tv/earliboy',
            ],
            [
                'name' => 'EinfachGustaf',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/c/EinfachGustaf',
                'twitch_url' => null,
            ],
            [
                'name' => 'Exsl95',
                'is_new' => false,
                'twitch_username' => 'exsl95',
                'youtube_url' => 'https://www.youtube.com/@Exsl95',
                'twitch_url' => 'http://twitch.tv/exsl95',
            ],
            [
                'name' => 'Fabo',
                'is_new' => false,
                'twitch_username' => 'Fabo',
                'youtube_url' => 'https://www.youtube.com/c/TheFaboHD',
                'twitch_url' => 'http://twitch.tv/Fabo',
            ],
            [
                'name' => 'Faister',
                'is_new' => false,
                'twitch_username' => 'faister',
                'youtube_url' => 'https://www.youtube.com/@Faister',
                'twitch_url' => 'https://www.twitch.tv/faister',
            ],
            [
                'name' => 'Felikah',
                'is_new' => false,
                'twitch_username' => 'felikah',
                'youtube_url' => 'https://www.youtube.com/@Felikah',
                'twitch_url' => 'http://twitch.tv/felikah',
            ],
            [
                'name' => 'Fibii',
                'is_new' => false,
                'twitch_username' => 'fibii',
                'youtube_url' => 'https://www.youtube.com/channel/UCx1_fN0iR1IIpNdAOnVKWAA',
                'twitch_url' => 'http://twitch.tv/fibii',
            ],
            [
                'name' => 'FilowLIVE',
                'is_new' => false,
                'twitch_username' => 'filow',
                'youtube_url' => 'https://www.youtube.com/@FilowLIVE',
                'twitch_url' => 'http://twitch.tv/filow',
            ],
            [
                'name' => 'Flocke',
                'is_new' => false,
                'twitch_username' => 'flocke',
                'youtube_url' => 'https://www.youtube.com/c/FlockeLP',
                'twitch_url' => 'https://www.twitch.tv/flocke',
            ],
            [
                'name' => 'Fuxel',
                'is_new' => false,
                'twitch_username' => 'fuxelbau',
                'youtube_url' => 'https://www.youtube.com/@Fuxel',
                'twitch_url' => 'http://twitch.tv/fuxelbau',
            ],
            [
                'name' => 'Gamerstime',
                'is_new' => false,
                'twitch_username' => 'gtimetv',
                'youtube_url' => 'https://www.youtube.com/c/Gamerstime',
                'twitch_url' => 'https://www.twitch.tv/gtimetv',
            ],
            [
                'name' => 'gamingguidesde',
                'is_new' => false,
                'twitch_username' => 'gamingguidesde',
                'youtube_url' => 'https://www.youtube.com/c/gamingguidesde',
                'twitch_url' => 'https://www.twitch.tv/gamingguidesde',
            ],
            [
                'name' => 'GommeHD',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@GommeHD',
                'twitch_url' => null,
            ],
            [
                'name' => 'Halbzwilling',
                'is_new' => false,
                'twitch_username' => 'halbzwilling',
                'youtube_url' => 'https://www.youtube.com/halbzwilling',
                'twitch_url' => 'http://twitch.tv/halbzwilling',
            ],
            [
                'name' => 'Henkenbergen',
                'is_new' => false,
                'twitch_username' => 'henke',
                'youtube_url' => 'https://www.youtube.com/@henkenbergen',
                'twitch_url' => 'http://twitch.tv/henke',
            ],
            [
                'name' => 'HerrBergmann',
                'is_new' => false,
                'twitch_username' => 'herrbergmann',
                'youtube_url' => 'https://www.youtube.com/c/herrbergmann',
                'twitch_url' => 'https://www.twitch.tv/herrbergmann',
            ],
            [
                'name' => 'HoneyPuu',
                'is_new' => false,
                'twitch_username' => 'honeypuu',
                'youtube_url' => 'https://www.youtube.com/c/HoneyPuu',
                'twitch_url' => 'http://twitch.tv/honeypuu',
            ],
            [
                'name' => 'iOser100',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/c/iOser100',
                'twitch_url' => null,
            ],
            [
                'name' => 'Jaybee',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@JaybeeMangror',
                'twitch_url' => null,
            ],
            [
                'name' => 'kadl',
                'is_new' => false,
                'twitch_username' => 'kadl',
                'youtube_url' => 'https://www.youtube.com/@kadl',
                'twitch_url' => 'http://twitch.tv/kadl',
            ],
            [
                'name' => 'Kedos',
                'is_new' => false,
                'twitch_username' => 'Kedos',
                'youtube_url' => 'https://www.youtube.com/channel/UCJylTAwdSFEOKEhnNOjk1Lg',
                'twitch_url' => 'http://twitch.tv/Kedos',
            ],
            [
                'name' => 'krokoboss',
                'is_new' => false,
                'twitch_username' => 'krokoboss',
                'youtube_url' => 'https://www.youtube.com/@krokoboss',
                'twitch_url' => 'http://twitch.tv/krokoboss',
            ],
            [
                'name' => 'LarsLP',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@LarsLP',
                'twitch_url' => null,
            ],
            [
                'name' => 'LetsHugo',
                'is_new' => false,
                'twitch_username' => 'letshugotv',
                'youtube_url' => 'https://www.youtube.com/c/LetsHugo',
                'twitch_url' => 'http://twitch.tv/letshugotv',
            ],
            [
                'name' => 'LOGO',
                'is_new' => false,
                'twitch_username' => 'logo',
                'youtube_url' => 'https://www.youtube.com/@logo',
                'twitch_url' => 'https://www.twitch.tv/logo',
            ],
            [
                'name' => 'Mahluna',
                'is_new' => false,
                'twitch_username' => 'mahluna',
                'youtube_url' => 'https://www.youtube.com/channel/UC44X9EapFGwQOo5OCN0BpJg',
                'twitch_url' => 'http://twitch.tv/mahluna',
            ],
            [
                'name' => 'MAXIMALSCHRADIN',
                'is_new' => false,
                'twitch_username' => 'maximal_schradin',
                'youtube_url' => 'https://www.youtube.com/@maximalschradin',
                'twitch_url' => 'http://twitch.tv/maximal_schradin',
            ],
            [
                'name' => 'merleperle',
                'is_new' => false,
                'twitch_username' => 'merleperle',
                'youtube_url' => 'https://www.youtube.com/channel/UCo1MY0mLicMfa023oxM5k_A',
                'twitch_url' => 'http://twitch.tv/merleperle',
            ],
            [
                'name' => 'Mexify',
                'is_new' => false,
                'twitch_username' => 'mexify',
                'youtube_url' => 'https://www.youtube.com/@mexify',
                'twitch_url' => 'http://twitch.tv/mexify',
            ],
            [
                'name' => 'mienah',
                'is_new' => false,
                'twitch_username' => 'mienah_',
                'youtube_url' => 'https://www.youtube.com/@mienahLIVE',
                'twitch_url' => 'http://twitch.tv/mienah_',
            ],
            [
                'name' => 'mooo',
                'is_new' => false,
                'twitch_username' => 'mooo_',
                'youtube_url' => 'https://www.youtube.com/@MOOO__',
                'twitch_url' => 'http://twitch.tv/mooo_',
            ],
            [
                'name' => 'Niek',
                'is_new' => false,
                'twitch_username' => 'niekbeats',
                'youtube_url' => 'https://www.youtube.com/@Niekbeats',
                'twitch_url' => 'http://twitch.tv/niekbeats',
            ],
            [
                'name' => 'nooreax',
                'is_new' => false,
                'twitch_username' => 'nooreax',
                'youtube_url' => 'https://www.youtube.com/@nooreax',
                'twitch_url' => 'http://twitch.tv/nooreax',
            ],
            [
                'name' => 'NQRMAN',
                'is_new' => false,
                'twitch_username' => 'NORMAN',
                'youtube_url' => 'https://www.youtube.com/c/NQRMAN',
                'twitch_url' => 'http://twitch.tv/NORMAN',
            ],
            [
                'name' => 'notGambo',
                'is_new' => false,
                'twitch_username' => 'notgambo',
                'youtube_url' => 'https://www.youtube.com/@notGambo',
                'twitch_url' => 'https://www.twitch.tv/notgambo',
            ],
            [
                'name' => 'noway4u',
                'is_new' => false,
                'twitch_username' => 'noway4u_sir',
                'youtube_url' => 'https://www.youtube.com/@Noway4u',
                'twitch_url' => 'http://twitch.tv/noway4u_sir',
            ],
            [
                'name' => 'Paluten',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/@Paluten',
                'twitch_url' => null,
            ],
            [
                'name' => 'Papaplatte',
                'is_new' => false,
                'twitch_username' => 'papaplatte',
                'youtube_url' => 'https://www.youtube.com/user/papaplatte',
                'twitch_url' => 'http://twitch.tv/papaplatte',
            ],
            [
                'name' => 'Petrit',
                'is_new' => false,
                'twitch_username' => 'petrit',
                'youtube_url' => 'https://www.youtube.com/PetritLP',
                'twitch_url' => 'http://twitch.tv/petrit',
            ],
            [
                'name' => 'Pumi',
                'is_new' => false,
                'twitch_username' => 'pumithecat',
                'youtube_url' => 'https://www.youtube.com/@PumiTheCat',
                'twitch_url' => 'http://twitch.tv/pumithecat',
            ],
            [
                'name' => 'Reeze',
                'is_new' => false,
                'twitch_username' => 'reeze',
                'youtube_url' => 'https://www.youtube.com/@Reeze',
                'twitch_url' => 'http://twitch.tv/reeze',
            ],
            [
                'name' => 'rewinside',
                'is_new' => false,
                'twitch_username' => 'rewinside',
                'youtube_url' => 'https://www.youtube.com/@rewinside',
                'twitch_url' => 'http://twitch.tv/rewinside',
            ],
            [
                'name' => 'RGB Pixl',
                'is_new' => false,
                'twitch_username' => 'rgbpixl',
                'youtube_url' => 'https://www.youtube.com/c/rgbpixl',
                'twitch_url' => 'https://www.twitch.tv/rgbpixl',
            ],
            [
                'name' => 'Rotpilz',
                'is_new' => false,
                'twitch_username' => 'rotpilz',
                'youtube_url' => 'https://www.youtube.com/c/Rotpilz',
                'twitch_url' => 'http://twitch.tv/rotpilz',
            ],
            [
                'name' => 'Rumathra',
                'is_new' => false,
                'twitch_username' => 'rumathra',
                'youtube_url' => 'https://www.youtube.com/c/Rumathra',
                'twitch_url' => 'http://twitch.tv/rumathra',
            ],
            [
                'name' => 'RvNx Mango',
                'is_new' => false,
                'twitch_username' => 'rvnxmango',
                'youtube_url' => 'https://www.youtube.com/channel/UCl9h2O2Gfbj-njltH8gQsog',
                'twitch_url' => 'http://twitch.tv/rvnxmango',
            ],
            [
                'name' => 'Ryole',
                'is_new' => false,
                'twitch_username' => 'Ryole',
                'youtube_url' => 'https://www.youtube.com/c/ryole',
                'twitch_url' => 'http://twitch.tv/Ryole',
            ],
            [
                'name' => 'Sebo',
                'is_new' => false,
                'twitch_username' => 'sebo',
                'youtube_url' => 'https://www.youtube.com/c/Sebooo',
                'twitch_url' => 'http://twitch.tv/sebo',
            ],
            [
                'name' => 'Sintica',
                'is_new' => false,
                'twitch_username' => 'sintica',
                'youtube_url' => 'https://www.youtube.com/@Sintica',
                'twitch_url' => 'http://twitch.tv/sintica',
            ],
            [
                'name' => 'skate702',
                'is_new' => false,
                'twitch_username' => 'skate702',
                'youtube_url' => 'https://www.youtube.com/c/skate702',
                'twitch_url' => 'http://twitch.tv/skate702',
            ],
            [
                'name' => 'SpaceMitX',
                'is_new' => false,
                'twitch_username' => 'spacemitx',
                'youtube_url' => 'https://www.youtube.com/@SpaceMitX',
                'twitch_url' => 'http://twitch.tv/spacemitx',
            ],
            [
                'name' => 'SparkofPhoenix',
                'is_new' => false,
                'twitch_username' => 'sparkofphoenixtv',
                'youtube_url' => 'https://www.youtube.com/user/SparkofPhoenix',
                'twitch_url' => 'http://de.twitch.tv/sparkofphoenixtv',
            ],
            [
                'name' => 'Stegi',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => 'https://www.youtube.com/user/SparkofPhoenix',
                'twitch_url' => 'https://www.youtube.com/c/byStegi',
            ],
            [
                'name' => 'techtastisch',
                'is_new' => false,
                'twitch_username' => 'techtastisch',
                'youtube_url' => 'https://www.youtube.com/@Techtastisch',
                'twitch_url' => 'http://twitch.tv/techtastisch',
            ],
            [
                'name' => 'TheJoCraft',
                'is_new' => false,
                'twitch_username' => 'thejocraft_live',
                'youtube_url' => 'https://www.youtube.com/c/thejocraft',
                'twitch_url' => 'https://www.twitch.tv/thejocraft_live',
            ],
            [
                'name' => 'tobifas',
                'is_new' => false,
                'twitch_username' => 'askationyt',
                'youtube_url' => 'https://www.youtube.com/@tobifas',
                'twitch_url' => 'http://twitch.tv/askationyt',
            ],
            [
                'name' => 'TolkinLoL',
                'is_new' => false,
                'twitch_username' => null,
                'youtube_url' => null,
                'twitch_url' => null,
            ],
            [
                'name' => 'Trymacs',
                'is_new' => false,
                'twitch_username' => 'trymacs',
                'youtube_url' => 'https://www.youtube.com/c/Trymacs',
                'twitch_url' => 'http://twitch.tv/trymacs',
            ],
            [
                'name' => 'Urutox',
                'is_new' => false,
                'twitch_username' => 'urutox',
                'youtube_url' => 'https://www.youtube.com/@Urutox',
                'twitch_url' => 'http://twitch.tv/urutox',
            ],
            [
                'name' => 'Veni',
                'is_new' => false,
                'twitch_username' => 'VeniCraft',
                'youtube_url' => 'https://www.youtube.com/@VeniCraft',
                'twitch_url' => 'http://twitch.tv/VeniCraft',
            ],
            [
                'name' => 'Wichtiger',
                'is_new' => false,
                'twitch_username' => 'wichtiger',
                'youtube_url' => 'https://www.youtube.com/@Wichtiger',
                'twitch_url' => 'http://twitch.tv/wichtiger',
            ],
            [
                'name' => 'Zander',
                'is_new' => false,
                'twitch_username' => 'Zander',
                'youtube_url' => 'https://www.youtube.com/c/zander',
                'twitch_url' => 'http://twitch.tv/Zander',
            ],
            [
                'name' => 'zarbexLIVE',
                'is_new' => false,
                'twitch_username' => 'zarbex',
                'youtube_url' => 'https://www.youtube.com/@zarbexlive',
                'twitch_url' => 'http://twitch.tv/zarbex',
            ],
            [
                'name' => 'Zinus',
                'is_new' => false,
                'twitch_username' => 'Zinus',
                'youtube_url' => 'https://www.youtube.com/@Zinus',
                'twitch_url' => 'http://de.twitch.tv/Zinus',
            ],
        ];

        foreach ($participants as $participant) {
            Participant::create($participant);
        }
    }
}